---
version: '3'
services:

    master:
      build: jenkins-master
      
      image: edg-jenkins-master
      container_name: edg-jenkins
      ports:
        - "50000:50000"
        - "8080:8080"
